plugins:
  - uses:
    - plugin: ishowvel/daemon-disqualifier:compute.yml@testing
      with:
        disqualification: "2 minutes"
        warning: "1 minutes"
        watch:
          optOut:
            - "repoName"
            - "repoName2"
        eventWhitelist:
          - "pull_request.review_requested"
          - "pull_request.ready_for_review"
          - "pull_request_review_comment.created"
          - "issue_comment.created"
          - "push"
    
