- plugin: ishowvel/daemon-disqualifier:compute.yml@testing
  type: github
  with:
    disqualification: "2 minutes"
    warning: "1 minutes"
    watch:
      optOut:
        - "repoName"
        - "repoName2"
    eventWhitelist: # these are the tail of the webhook event i.e pull_request.review_requested
      - "review_requested"
      - "ready_for_review"
      - "commented"
      - "committed"
